### ISSUE TITLE
Při vytváření objektu se nezobrazí náhledy

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#100]
Při zpracování se vyskytla chyba.
![thumbs](https://cloud.githubusercontent.com/assets/5516936/21761933/58b99570-d656-11e6-84d2-209bf46fa343.png)

**Comment by MartinRumanek** [comment]
V případě instalace, kde jsou ven vyčleněné konfigurační soubory, je potřeba aktualizovat compress.sh, který se měnil v listopadu (https://github.com/moravianlibrary/MEditor/blob/master/resources/djatoka/bin/compress.sh).
