### ISSUE TITLE
Vložení se nezdařilo: Chyby max. number of attempts has been reached

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#102]
Jde o připojování nového objektu k existujícímu.
![vlozeni](https://cloud.githubusercontent.com/assets/5516936/21771350/4ce5d674-d687-11e6-9768-9cf9275b81b1.png)

**Comment by MartinRumanek** [comment]
Nedaří se mi to zreplikovat na testovacích datech, ročník se mi v pořádku připojí, jen je ho potřeba ručně reindexovat (to je ale na jiný bug)

**Comment by Jenyk** [comment]
Tahle hláška se v MZK objevovala, když byl problém s fedorou.

**Comment by MartinRumanek** [comment]
A asi to tak i bylo, pravděpodobně za chybu mohl včerejší nestotatek místa na serveru s Fedorou, protože dnes se už chyba neprojevuje.
