### ISSUE TITLE
Načtení obrázků někdy načte vše, někdy ne a někdy hodí chybu Bad authorization class

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#103]
Po načtení metadat se né vždy zobrazí všechny obrázky. Někdy se zobrazí všechny, někdy posledních pár chybí a někdy to háže chybu Bad authorization class. Pokaždé, když to dám načíst znova, tak se chová náhodně jedním ze tří způsobů. Tady jsou screeny:

https://s6.postimg.org/omcmntpe9/Screenshot_20170110_092241.png
https://s6.postimg.org/6823jud3l/Screenshot_20170110_092316.png
https://s6.postimg.org/4hj2icvkh/Screenshot_20170110_092340.png

verze prohlížeče: Firefox 50.1.0

**Comment by MartinRumanek** [comment]
Testovací prostředí (čistý Debian Jessie s instalací Docker podle oficiálního návodu):

verze:
```
Firefox 50.1.0
Docker version 1.12.5, build 7392c3b
docker-compose version 1.9.0, build 2585387
```

verze obrazu:
```
docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
moravianlibrary/meditor              latest              e3bf1fae727a        28 hours ago        2.239 GB
```
Je i s tvými daty všechno v pořádku. Máš tyto verze (především `IMAGE ID`) stejné?

**Comment by FoxKyong** [comment]
Jo, to sedí. A data jsou taky dobrá, zkoušel jsem to ještě na dalších a dělá to pořád.

**Comment by black23** [comment]
Potvrzuji toto chvání i naší instalaci s CentOS, Firefox stejný.

**Comment by MartinRumanek** [comment]
@black23 a po aktualizaci stránky se to zobrazí v pořádku nebo jsi přesměrovaný na login stránku?

**Comment by MartinRumanek** [comment]
Konečně se mi podařila replikovat situace, kdy se nenačtou všechny obrázky. Bohužel se to chová jako heisenbug.
