### ISSUE TITLE
Převod metadat z MARC 21 (originInfo)

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#106]
Do metadat se nepřevedou všechny znaky z MARC21, např. hranaté závorky v polích originInfo (př. jedna závorka se převede, druhá ne nebo tam není žádná). Žádoucí je, aby se stáhlo do polí všechno včetně hranatých závorek, tak jak je to v záznamu.

**Comment by MartinRumanek** [comment]
Chyba je v konverzní šabloně z MARC21 na MODS.

_________

Používáme mírně upravenou šablonu RDA, jediná změna čím se lišíme vznikla na základě #74:
https://github.com/moravianlibrary/MEditor/blob/master/resources/xml/MARC21slim2MODS3.xsl

RDA šablona vychází ze staré šablony Kongresové knihovny (z února 2012)

Šablona Kongresové knihovny se dále vyvíjí a bylo by tedy vhodné, kdyby se změny do RDA změny  průběžně propisovaly.
https://github.com/LibraryOfCongress/MarcMods3.5xsl/blob/master/MARC21slim2MODS3-5.xsl

**Porovnání výstupů** 
(vlevo_ naše šablona vycházející z RDA, vpravo aktuální šablona Kongresové knihovny)
https://gist.github.com/MartinRumanek/18eebece728e6b52d38cf4a403456d06/revisions

pozn. dokonce se zdá, že šablona z kongresovky řeší správně shelfLocator z našeho issue #74
