### ISSUE TITLE
Hranaté závorky v dateIssued

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#107]
Pokud jsou v poli dateIssued v originInfo v MODS hranaté závorky, nejde překlikávat do jiných záložek, ani publikovat dokument. V záznamu být ale musí. Mělo by to upozornit, ale dovolit publikování i překliknutí jinam. Dřív to šlo.

**Comment by MartinRumanek** [comment]
Ve Firefoxu se chyba neprojevuje, pouze v Chrome.
