### ISSUE TITLE
Obrázky nejdou načíst pokud imageserver neběží pod rootem

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#108]
Imageserver nemůže načíst obrázky nahrané přes MEditor pokud imageserver neběží pod rootem. Je potřeba jiná práva (nejlépe asi 755 nebo 744) na vytvořenou složku a obrázky v imageserveru.

**Comment by MartinRumanek** [comment]
Editor vytváří obrázky pod právy:
```
pro adresáře: drwxr-x---
pro soubory: -rw-r-----.
```

Nově je teď nově možné v docker-compose.yml zadefinovat uživatele pod kterým MEditor poběží (a pod tím stejným uživatelem se ti uloží obrázky do datového adresáře imageserveru).

Např:
```
meditor:
  image: moravianlibrary/meditor
  user: "1001:1001"
```

Když si tam dáš UID nebo alespoň GID uživatele imageserveru, tak by ti to mělo fungovat i bez úpravy práv.

Práva dodělat můžu, ale takto mi to přijde systémovější.

**Comment by FoxKyong** [comment]
Tak nefunguje. Opět mi to vytvořilo
> drwxr-x--- 2 root      root

**Comment by FoxKyong** [comment]
Tak stále nefunkční, je potřeba, aby i ty práva byly 755.

**Comment by MartinRumanek** [comment]
> Tak nefunguje. Opět mi to vytvořilo
drwxr-x--- 2 root root

Změna UID funguje, toto bylo způsobenou konfigurací  SSHFS (který se logoval jako root).

\+ Nově jsou adresáře tvořeny s právy 755 a soubory 644. Možné překonfigurovat proměnnou prostředí UMASK.
