### ISSUE TITLE
Nenačítání vlastních transformačních šablon MARC

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#109]
MEditor nenačítá vlastní šablony xsl jako předtím. Pro nás se to týká MARC21slim2MODS3.xsl, kde máme úpravu kvůli načítání signatury, kterou náš Aleph předává přes pole 996 c.
V sekci volume v .yml jsem nastavil připojení adresáře s xsl do kontejneru do adresáře /opt/app-root/src/.meditor/xsl. Když se za běhu MEditoru do kontejneru podívám, tak ty xsl tam jsou, takže je MEditor asi nenačítá, i když jsou tam, kde by měli být.

**Comment by MartinRumanek** [comment]
Promiň, že jsem se k tomu dostal až teď, myslel jsem si, že to bude složitější, ale nakonec by mělo stačit přejmenovat adresář `xsl` na `xml`. 

A podle kódu to takto bylo vždy, to je nejdivnější - možná ti toto fungovalo s vývovojou verzí od @jirikrepl

**Comment by FoxKyong** [comment]
Tak vyřešeno. Změnil jsem připojení adresáře do /opt/app-root/src/.meditor/xml a už to tu šablonu načítá.

**Comment by MartinRumanek** [comment]
Super. Díky za zprávu!
