### ISSUE TITLE
Poslední verze MEditoru - nejde se přihlásit (HTTP Status 500)

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#111]
Po přihlášení MEditor skončí na chybě:
HTTP Status 500 - ldap:389; nested exception is javax.naming.CommunicationException: ldap:389 [Root exception is java.net.UnknownHostException: ldap]

![meditor_chyba](https://cloud.githubusercontent.com/assets/2877720/24149654/80042472-0e43-11e7-868d-ad327be5cfda.PNG)

**Comment by leiblix** [comment]
Včera jsem na docker hub pushnul aktuální verzi a zároveň ji nasazoval do MZK a bylo to v pořádku. Prosím vyzkoušej a kdyby to nefungovalo, neváhej issue znovuotevřít.
