### ISSUE TITLE
imageServer/recordingServer.known vs unknown

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/MEditor#114]
Jaký mají význam konfigurační properties imageServer.unknown a recordingServer.unknown, resp. jaký je rozdíl mezi known a unknown? 
Jasně, jsou to adresáře, kam se vkládají výstupní jp2 soubory z konverze z třeba jpg, ale proč jsou ty adresáře dva?
Protože existuje třeba jen imageServer.url, a ne imageServer.url.known a imageServer.url.unknown, takže fakticky dostupné pak budou jenom known věci.

**Comment by leiblix** [comment]
known je pro dokumenty, které mají známé Sysno - na základě toho se to ukládá do imageserveru v pěkné struktuře (podadresáře po třech znacích, tři úrovně - sysno má devět znaků)
unknown je pro ostatní dokumenty - ty se ukládají do ploché úrovně

**Comment by rzeh4n** [comment]
Super, díky za vysvětlení.
