### ISSUE TITLE
haluze s datem vydani

### ISSUE THREAD

**Issue by pavluska** [moravianlibrary/MEditor#14]
zadam do MODS origin - dateIssued datum 30.04.1945 a prepise se mi na 04.30.1945 a nejde to zmenit... http://kramerius.mzk.cz/search/handle/uuid:acfcd38f-7b9a-4e4d-8360-2fa642436064

v DC se pak 30.04.1945 prepise na uplnou haluz viz obrazek

![snimek obrazovky 2015-04-13 v 20 22 38](https://cloud.githubusercontent.com/assets/3939120/7122573/b5f077a2-e21c-11e4-9370-92f28da46c20.png)

**Comment by MartinRumanek** [comment]
Pozn. to je trochu haluz potomek https://github.com/moravianlibrary/MEditor/blob/master/editor-common/editor-common-client/src/main/java/cz/mzk/editor/client/view/window/EditorDateItem.java, který imho nepěkně upravuje chování komponenty smartgwt....

**Comment by MartinRumanek** [comment]
@LenkaDamborska Prosím, kde zjistím, jaké všechny hodnoty jsou validní pro ten mods origin? (a pro ten DC date by se mi to také hodilo)

**Comment by LenkaDamborska** [comment]
Myslíš tvar data vydání v dateIssued elementu? Ideálně DD.MM.RRRR. Jinak zbytek je tady: https://docs.google.com/spreadsheets/d/1wyslvJa1vOLUwOSQ7s3kRnKB82A08mq1ITK5lXII_9Y/edit#gid=850398819

**Comment by MartinRumanek** [comment]
Vyřešeno spolu s #107
