### ISSUE TITLE
Přihlašování přes google account

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#17]
V janrainu přestalo fungovat přihlašování přes google účet, protože Google ukončil podporu. viz https://support.google.com/accounts/answer/6135882?authuser=0

**Comment by MartinRumanek** [comment]
Janrain je spravený, ale ještě nastává tato chyba https://support.janrain.com/hc/communities/public/questions/203138073-Trying-to-login-via-google-invalid-client-no-support-email

**Comment by MartinRumanek** [comment]
Kromě aktualizace janrainu bylo potřeba ještě přidat v google developer konzoli e-mail. (dle https://support.janrain.com/hc/communities/public/questions/203138073-Trying-to-login-via-google-invalid-client-no-support-email)

**Comment by black23** [comment]
Takže i nám už bude tohle fungovat? Nebo stále přes fake LDAP?

**Comment by MartinRumanek** [comment]
Nebude, aby to fungovalo, musel by být editor dostupný veřejně z internetu (musí na něho janrain vidět). 

Ale fake LDAP je pryč, máte už vlastní, viz https://github.com/moravianlibrary/MEditor/wiki/P%C5%99id%C3%A1v%C3%A1n%C3%AD-u%C5%BEivatel%C5%AF-v-aplikaci-phpldapadmin

heslo uživatele do toho ldapu najdeš v docker-compose.yml

**Comment by black23** [comment]
Killer app :-) Diky!
