### ISSUE TITLE
Konfigurovatelná konverzní šablona marc na mods

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#20]
Různé knihovny můžou mít metadata na různých místech, řešením je, aby si mírně upravili konverzní šablonu, ta je nyní schovaná v kontejneru.

@FoxKyong - u tebe to vyřeší sysno
@black23 - u tebe to vyřeší siglu řešenou zde https://github.com/moravianlibrary/kramerius/issues/13

**Comment by black23** [comment]
Souhlas
