### ISSUE TITLE
Cesta k OCR v uložené struktuře

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#23]
V tabulce tree_structure_node by se měla ukládat relativní cesta k OCR, nikoliv absolutní. Teď když dojde k přesunutí importního adresáře, rozbijou se všechny uložené dokumenty

**Comment by black23** [comment]
Jak se tedy chovat v pripade, ze musime ve vstupni fronte neco predelat? Nahrat vse opet do puvodniho adresare? Cas od casu se stane, ze prijdeme na nejake chyby, napr. nespravne nazvy souboru, kdy nesedi OCR k obrazku.

**Comment by MartinRumanek** [comment]
Toto issue popisuje trochu něco jiného (když se přesune celá složka import a změní se její lokace v nastavení).

Ale to na co se ptáš ty ano, měly byste se držet té konvence co si vymyslel a v případě špatných souborů je potřeba je přepsat. Ale pokud se mění zásadně struktura, tak tu uloženou strukturu budete ještě asi upravovat - to normálně jde - do chyby to případně spadne, až když se pokusíte o import.

**Comment by black23** [comment]
Ale u nás snad k přesunu celé importní složky nedošlo, nebo ano?
