### ISSUE TITLE
Model monograph is not present in repository

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#24]
Při načítání struktury pro import to hlásí chybu, že model monograph neexistuje.

https://gist.github.com/FoxKyong/e4a272976933c6602e02

**Comment by MartinRumanek** [comment]
Mohl bys mi ještě zkopírovat celý obsah http://kramerius.kr-olomoucky.cz:8180/fedora/get/model:monograph ?

Jakou máš verzi Fedory?

**Comment by FoxKyong** [comment]
Verze fedory je 3.6.2
https://gist.github.com/FoxKyong/0154ecd3792a847abb4b

**Comment by MartinRumanek** [comment]
Máš v environment zadefinovanou proměnnou  fedoraVersion=3.6.2?

**Comment by FoxKyong** [comment]
Jj, je to tam.

**Comment by MartinRumanek** [comment]
Jo, už se mi to podařilo zreplikovat. Ale vypadá to, že to na GUI žádný vliv, nemá, ne?

**Comment by FoxKyong** [comment]
To snad ne, ale nemáme teď žádnou monografii připravenou na import, jestli se to u toho v něčem neprojeví pak.
