### ISSUE TITLE
ERROR (InputQueueItemDAOImpl.java:210) - Query: NULL

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#25]
Tak ještě jeden problém, když něco přidávám, tak se v logu občas objeví toto. Tahle chyba se objeví hned před a po konverzi obrázku podle logu a celkem zdržuje, jestli je zrovna tohle ta příčina. Když tohle nastane, tak než můžu pokračovat s vytvářením struktury, tak to na tom zůstane tak 20 - 60 sekund. Teď právě přidávám mapy, které jdou celkem rychle, tak se to hodně projevuje, to čekání, když tohle vznikne. Někdy to převede a načte hned, ale někdy to zůstane na tom načítání celkem dlouho. Jak se to pak už načte, tak nic dalšího se v logu neobjeví, takže to bude asi ono.

https://gist.github.com/FoxKyong/0d5bf7f6b85a5f9e25f6

edit: opravil jsem čas, teď jsem čekal minutu, než to načetlo.

**Comment by FoxKyong** [comment]
Tak přidávám další dvě chyby k tomu. Akorát se začala zaplňovat paměť a chyby jsou tyto:
`
05:51:31 ERROR (ConversionDAOImpl.java:121) - Select statement: NULL This statement has been closed.
05:51:59 ERROR (AbstractDAO.java:246) - Connection was not closed
`
Taky se to už zpomaluje a akorát opět spadlo spojení s databází, tak ho jdu restartovat.

**Comment by LenkaDamborska** [comment]
Nepodařilo se zreplikovat. Můžeme otevřít, pokud problém znovu nastane.
