### ISSUE TITLE
Občas se kramerius sekne při rychlé editaci dokumentů a následným publikováním

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#26]
Tak tohle se teď špatně popisuje. Ale jelikož se stalo už podruhé, tak to asi bude problém. Zatím se to stalo, když se otevřel nějaký objekt, tam rychlá editace, provedla se oprava a dalo se publikovat. Při stisknutí publikovat se celý MEditor sekne, takže ani jiný uživatel nemůže nic dělat. Přidávám screen a log. Ale v logu chyba není, skončí to na Processing action: GetRecentlyModified a chyba na screenu RPC failed: 0
Musím teda celý MEditor restartovat, aby to zase fungovalo.

https://gist.github.com/FoxKyong/fbc89bed5fd64f7353b4

![chyba](https://cloud.githubusercontent.com/assets/2877720/7723535/c620f716-fee9-11e4-9b83-d103d5390ff2.png)

**Comment by black23** [comment]
Potvrzuji toto chování.

**Comment by MartinRumanek** [comment]
Děje se to i v aktuální verzi? Nedaří se mi to replikovat.
