### ISSUE TITLE
Meditor negeneruje MP3 streamy

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#28]
MEditor pravděpodobně občas nevygeneruje mp3 streamy do audioserveru. 

Viz https://github.com/moravianlibrary/kramerius/issues/15

**Comment by svetlym** [comment]
Nejsem si úplně jistý, jestli jsem pochopil, co mám vyzkoušet, každopádně na http dotaz

http://kramerius4.mlp.cz/search/api/v5.0/item/uuid:f8e8c937-b5ce-4fe8-b69a-40cd1813364e/streams/

jsem dostal odpověď:

{"DC":{"label":"Dublin Core Record for this object","mimeType":"text/xml"},"BIBLIO_MODS":{"label":"BIBLIO_MODS description of current object","mimeType":"text/xml"},"IMG_FULL":{"label":"","mimeType":"image/jpeg"},"IMG_PREVIEW":{"label":"","mimeType":"image/jpeg"},"IMG_THUMB":{"label":"","mimeType":"image/jpeg"},"WAV":{"label":"Wav version of this audio track","mimeType":"audio/wav"},"MP3":{"label":"Mp3 version of this audio track","mimeType":"audio/mpeg"},"OGG":{"label":"Ogg Vorbis version of this audio track","mimeType":"audio/ogg"}}

http dotaz http://kramerius4.mlp.cz/search/api/v5.0/item/uuid:f8e8c937-b5ce-4fe8-b69a-40cd1813364e/streams/MP3 zobrazí přehrávač.

**Comment by MartinRumanek** [comment]
Tak u vás je to v pořádku. Díky.
