### ISSUE TITLE
Zarolování souborů ve výchozí pozici

### ISSUE THREAD

**Issue by Lenyska** [moravianlibrary/MEditor#31]
Bylo by možné, aby soubory (Vydání 01, 02, 03....) na levé straně ve stromě podstruktur byly ve výchozí pozici zarolované? Pomohlo by třeba i pole "zabalit vše", abych je mohla všechny najednou zarolovat a dostala se tak rychleji k níže vytvořeným souborům.

![vydani periodik](https://cloud.githubusercontent.com/assets/11989702/8871535/55bc7276-31f6-11e5-9d8e-643bff4fffdb.jpg)

Díky Lenka

**Comment by MartinRumanek** [comment]
Duplikát issue https://github.com/moravianlibrary/MEditor/issues/4
