### ISSUE TITLE
Pokus o připojení objektu k existujícímu končí chybou

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#32]
Při pokusu připojit objekt (číslo) k existujícímu objektu (periodikum, ročník) operace velmi dlouho trvá a nakonec skončí hláškou "reindexace se nepodařila". Nové číslo v K5 není. Obecně proces vkládání trvá výrazně delší dobu, než tomu bylo v minulosti.
![medit2](https://cloud.githubusercontent.com/assets/5516936/8927281/975af9b4-3516-11e5-8c06-4da2297e5acb.png)
![medit3](https://cloud.githubusercontent.com/assets/5516936/8927280/97598d5e-3516-11e5-8f5e-3776f756c4c1.png)
![medit4](https://cloud.githubusercontent.com/assets/5516936/8927279/9759116c-3516-11e5-89a7-2bab858d82cb.png)
![medit5](https://cloud.githubusercontent.com/assets/5516936/8927282/975e8796-3516-11e5-9e5d-11f260b5440b.png)

**Comment by MartinRumanek** [comment]
Bylo špatně heslo, ale editor by měl stejně správnot hesla hlídat.

**Comment by black23** [comment]
Co to pripsat do te chybove hlasky?

**Comment by MartinRumanek** [comment]
Spíš bych to kontroloval na home stránce, kde se kontroluje zda je kramerius dostupný, ale to už s tímto issue nesouvisí.
