### ISSUE TITLE
Přejmenoval se název

### ISSUE THREAD

**Issue by Lenyska** [moravianlibrary/MEditor#33]
Po zpracování zpravodaje v meditu a následném připojení na existující digitální objekt se zpracování zdařilo, ale přejmenovaly se čísla z původního 01, 02, 03 na název "Českotřebovský zpravodaj 01 ....
![nazev zpravodaje](https://cloud.githubusercontent.com/assets/11989702/9130790/1b433c60-3ce6-11e5-9059-59b40dc90de3.jpg)
a navíc se rozmnožily
![rozmnozeniny](https://cloud.githubusercontent.com/assets/11989702/9130804/31bdc988-3ce6-11e5-8236-8928bb67b9ba.jpg)
Můžete se prosím na to někdy mrknout? Předem děkuji

**Comment by MartinRumanek** [comment]
Rozmožování dokumentů jsem popsal ve zvláštním issue https://github.com/moravianlibrary/MEditor/issues/41. Budu to v blízké době řešit.

Přejmenování má na starosti indexační šablona Krameria, ta byla pravděpodobně v jeho verzi 5.1.1 chybná. Aktualizoval jsem vám Kramerius na verzi 5.2.0, po reindexaci periodika by se měly názvy spravit.
