### ISSUE TITLE
Podpora nového standardu RDA

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#34]
ukázka záznamu https://aleph.mzk.cz/F/U9MEDM1J7JKBG54KJKTDURU1YETHET8P4U94ATL28Q9VKDPI2J-01568?func=full-set-set&set_number=587669&set_entry=000001&format=001

viz http://www.ndk.cz/aktuality/novinky-titulni-strana/transformacni-sablona-projektu-ndk

**Comment by MartinRumanek** [comment]
V původní šabloně máme nějaké změny specifické pro MZK.

 <shelfLocator> (asi signatura) se bere marc:datafield[@tag=910] a týká se to jen monografií, toto chceme v RDA šabloně zachovat? Proč jsme v tomto specifičtí?

@LenkaDamborska Nejsou ještě náhodou nějaké jiné věci, čím se lišíme od standardu a je to potřeba zohlednit ?

**Comment by LenkaDamborska** [comment]
Pole 910 b pro signaturu je standardní pole, které používají české knihovny (pole 9xx je národní pole). Jen MZK by v tom specifická být neměla. 
O nějakých dalších specificích MZK nevím.
