### ISSUE TITLE
Typy stránek

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#35]
V Krameriu přibyly nové typy stránek, měl by je umět zpracovávat i meditor

https://github.com/ceskaexpedice/kramerius/commit/d367f6d8e537a9a0a0cf255bd82ba85a11deea62

**Comment by MartinRumanek** [comment]
Kramerius podporuje 32 typů stránek https://github.com/ceskaexpedice/kramerius/blob/d367f6d8e537a9a0a0cf255bd82ba85a11deea62/search/src/java/k5client_cs.properties#L134

Ale editor jich podporuje jen 19:
![img](http://i.imgur.com/v1mn5Jg.png)

Co s tím? Necháme to tak, rozšříříme to, nebo to uděláme konfigurovatelné :-)?

**Comment by LenkaDamborska** [comment]
Zatím to necháme tak a v případě nutnosti přidáme další typ strany. Ilustrace pro grafiky byla přidána.
