### ISSUE TITLE
Při spojování měsíců a následné publikování změny se objevila chyba s reindexací

### ISSUE THREAD

**Issue by Lenyska** [moravianlibrary/MEditor#36]
V meditu jsem zpracovala 4 měsíce jako vydání periodika. Přiřadila jsem je k již existujícímu digitálního objektu (ročník 2010). V krameriu se objevily ročníky zvlášť 2010/1-4 a 2010/5-12. Po zkopírování uuid obou ročníků v Krameriu - jsem si v meditu otevřela 2 okna a poté přetáhla měsíce z jednoho do druhého, abych měla celý rok u sebe. Změnu jsem dala "publikovat", objevilo se pole pro spuštění reindexačního procesu a po odkliknutí OK se na první pohled vůbec nic nestalo. Ani tabulka s dotazem na reindexaci nezmizela. Zkontrolovala jsem Kramerius a teď tam mám ročník 2010 pouze jednou a to s měsíci od 5-12 a první čtyři měsíce, které jsem vytvářela a chtěla původně přiřadit k ročníku 2010, zmizely.

**Comment by MartinRumanek** [comment]
Nedaří se mi problém replikovat. Firefox verze 39.
