### ISSUE TITLE
Nekompatibilita s verzí FireFoxu 41

### ISSUE THREAD

**Issue by FoxKyong** [moravianlibrary/MEditor#38]
Tak to píšu do issues. Po aktualizaci na verzi 41 nefunguje otevírání dvou objektů paralelně pro spojení. Ověřeno už na druhém pc, že to stejné začalo dělat po aktualizaci FireFoxu. Občas nefunguje zkratka CTRL-ALT-U a když funguje, tak objekt se otevře v obou oknech najednou místo jenom v jednom. Hlásí to často chybu 'Bad authorization class' a po pár pokusech MEditor spadne úplně.

Teď jenom teda, jestli je to zrovna nějaká chyba ve FireFoxu, co udělali, nebo už úmyslně měnili něco, co MEditor používá a je to už FireFoxem nepodporované nebo změněné.

**Comment by jirikrepl** [comment]
Můžete popsat podrobněji kroky, které vedou k chybě ve Firefoxu 41? Jaké kroky děláte pro otevření dvou dokumentů paralelně? Objeví se chyba Bad authorization class v konzoli JavaScriptu? Objeví se tato chyba pokaždé? (dají se kroky vedoucí k chybě vždy snadno replikovat?)
Klávesová zkratka Ctrl+Alt+u mi zatím ve FF41 pro Linux fungovala vždy.

**Comment by FoxKyong** [comment]
Takže děláme to tak, že otevřu dokument a dám editor částí. Tím se mi otevře v v MEditoru. Pak si otevřu druhý dokument a zkopíruji jeho UUID z URL. Pak dám CTRL-ALT-u a vložím to UUID. A je to. Takhle jsem to dělal vždycky.
Teď, pokaždé, jak otevřu ten první dokument, tak to hodí to Bad authorization class. Jakmile dám Ok na tu chybu, tak se to znova už po refreshi ani znovunačtení neobjeví. V konzoli jsem tu chybu neviděl. Po tom potvrzení té chyby se mi ten jeden editovaný dokument otevře automaticky v obou oknech. Jedno zavřu, tak CTRL-ALT-u, vložím UUID toho druhého dokumentu, co jsem chtěl, a otevře se to opět v obou oknech. Takže teď nejdou otevřít dva odlišné dokumenty paralelně. Testoval jsem to na Firefoxu 41 a 41.0.2. Testována verze pro linux i windows. Stejné chování je i v prohlížeči Konqueror. Takže chyba je dobře replikovatelná, zatím se mi od té doby nestalo, že by se povedli nějak otevřit paralelně dva různé dokumenty, jako předtím. A ta zkratka mi vždycky bohužel nefuguje. Ve virtualu na linuxu taky ne, na windowsu nevím, ten nepoužívám. Chtělo by to tlačítko na otevření, když to zrovna nefunguje.

**Comment by MartinRumanek** [comment]
Zkus prosím změnit about:config http://stackoverflow.com/questions/32840678/gwt-in-firefox41-repetitively-encodes-token-in-url/32907566#32907566

**Comment by MartinRumanek** [comment]
Musíme aktualizovat GWT na verzi 2.7 (teď máme 2.6), prozatím je problém vyřešit změnou konfigurační direktivy fe FF.

V about:config si změň konfigurační direktivu dom.url.getters_decode_hash na true. Problém se přestane vyskytovat.

**Comment by MartinRumanek** [comment]
Vyřešeno aktualizací GWT.
