### ISSUE TITLE
Editování stránek, Fedora 3.6.2

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#40]
V editačním módu se nančítají obrázky, pokud je použita Fedora 3.6.2. Ve Fedoře 3.5 se toho chování neprojeví.

http://i.imgur.com/24z3Lpy.png

**Comment by jirikrepl** [comment]
Zatím to řeší tento pull request https://github.com/moravianlibrary/MEditor/pull/45

**Comment by MartinRumanek** [comment]
Shrnu to, chybou není verze Fedory, ale chybou je špatný překlad imageserver.mzk.cz na ip adresu.

Uvnitř kontejneru:
root@6ea3caeb56be:/data/meditor# ping imageserver.mzk.cz
PING imageserver.mzk.cz (195.113.155.76): 56 data bytes
64 bytes from 195.113.155.76: icmp_seq=0 ttl=63 time=0.313 ms

mimo kontejner:
[rumanekm@docker-new medit.mzk.cz]$ ping imageserver.mzk.cz
PING imageserver (10.16.0.76) 56(84) bytes of data.

Když to jde přes 195.113.155.76 tak to zastaví firewall a projeví se to jak je zmíněno ve screenshotu.

Opravit se to dá např. tím, že se do docker-compose.yml připíše:

```
  extra_hosts:
    - "imageserver.mzk.cz:10.16.0.76"
```

Problém bylo, že se to kousne a do logu se nevypíše žádný error, to by měl zmiňovaný pull request opravovat.

**Comment by jirikrepl** [comment]
Opraveno tímto pull requestem https://github.com/moravianlibrary/MEditor/pull/46
