### ISSUE TITLE
Připojení čísla do ročníku vytvoří vytvoří duplicitní periodikum

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#41]
Připojování ročníků do už existijícího periodika funguje korektně, ale připojení čísla do už existujícího ročníku vytvoří **duplicitní periodikum** (s připojeným zpracovavajícím ročníkem).

Struktura vytvářeného periodika vypadá takto:
![struktura](http://i.imgur.com/dfpC4YV.png) 

Pokud je nižší úroveň připojená, měly by se vyšší úrovně při ingestu ignorovat.

**Comment by LenkaDamborska** [comment]
Podařilo se zopakovat a došlo ke vzniku nového duplicitního periodika s připojeným ročníkem uuid:74304b60-2558-11e5-8401-001018b5eb5c, který už je v tom původním periodiku. Číslo, které jsem se snažila k tomu ročníku připojit, tam ale není ani v jednom periodiku (mělo to být č. 308), takže výsledek je dupl. periodikum bez toho čísla.

**Comment by LenkaDamborska** [comment]
Takze vyreseno?? Supr.
Jinak smazali jste to, co jsem pri pokusu vytvorila? Uuid nahore. S Jirkou jsme se o tom bavili.

**Comment by MartinRumanek** [comment]
Aha, nesmazali - nevěděl jsem, mám :-)

**Comment by LenkaDamborska** [comment]
jo, to by bylo potřeba - visí tady http://kramerius.mzk.cz/search/handle/uuid:8d2df590-e436-4094-92c4-cd8e88751808, to je kořenové uuid.

**Comment by MartinRumanek** [comment]
@LenkaDamborska Ročník jsem odpojil a kořenové uuid smazal.
