### ISSUE TITLE
TLS v docker obrazu

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#44]
spin-off z https://github.com/moravianlibrary/kramerius/issues/43.

Umožnit v docker kontejneru specifikovat vlastní certifikáty (ty nemůžou být součástí přímo image) - asi nějak přes volumes, ve stylu jak se to řeší https://github.com/jwilder/nginx-proxy#ssl-support. Viz docker.mzk.cz:/data/docker-compose/proxy/docker-compose.yml (tam je certifikát pro docker.mzk.cz)

**Comment by jirikrepl** [comment]
ok neměl byt to být problém jen jak budeme mít ten certifikát, nastaví se to přes volumes

**Comment by jirikrepl** [comment]
Docker image meditu je upraven tak, že kopíruje z připojeného volume .keystore  soubor. 

TODO: kramerius-new.mzk.cz

**Comment by jirikrepl** [comment]
pro některé části medit.mzk.cz nefunguje autentizace s přiřazeným certifikátem. @MartinRumanek zatím certifikát odstranil.
