### ISSUE TITLE
Aktualizace UI knihoven a superdev

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#48]
Aktualizovat knihovny UI:
- GWT
- GWTP
- SmartGwt

a rozbehat superdev mod.

Zkousel jsem to uz ve vetvi https://github.com/moravianlibrary/MEditor/tree/update_gwtp, ale nefungoval ten superdev mod.

**Comment by jirikrepl** [comment]
Přidání SmartGwt pro verzi vyšší než 4.1 https://gist.github.com/jirikrepl/49e59b43cc9d29c9fd49

**Comment by jirikrepl** [comment]
po updatu nefunguje stránka pro nastavení administrátorských práv. 

V editoru nejde cokoliv vytvořit, hlásí, že uživatel nemá k tomu autorizaci.
