### ISSUE TITLE
MODS a ns2 

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#53]
Co je ns2 za formát a proč do něj editor balí MODS záznam? Některé záznamy mají ns2 ve foxml a už nějakou dobu přemýšlím nad tím, co to je. Nepodařilo se mi k tomu dohledat nějaké info.
Je to třeba tu: http://kramerius.mzk.cz/search/handle/uuid:64ac0900-a601-4899-860a-9f043f980042

**Comment by pavluska** [comment]
Ahoj,

to je akorat namespace. Byl tam nejak historicky z pocatku editoru tusim.
Ono se to jeste neopravilo? :)

P.

Dne čt 28. 1. 2016 9:45 uživatel LenkaDamborska <notifications@github.com>
napsal:

**Comment by LenkaDamborska** [comment]
Aha! Díky :-) Evidentně se to neřešilo. Otázka, jestli se to musí opravit. Mě spíš zajímalo, co to je.

**Comment by MartinRumanek** [comment]
Namespace je neco jako alias, ktery je zadefinovany v te prvni korenove znacce.

xmlns:ns2="http://www.loc.gov/mods/v3"

dulezite je co je na ten namaspace navazano (v tomto pripade xml schema modsu), je celkem jedno co v tom aliasu je, ta XML se berou jako ekvivalentni a kazdy parser co umi namespace si s tim poradi.

**Comment by honza-rychtar** [comment]
No taky jsem s tim bojoval. U weboveho klienta byl nejaky problem s namespacy u jQuery + Firofex, takze tam mam nejaky skaredy hack (ale funguje) a na Androidu jsem pro jistotu namespacy z xml pred zpracovanim odstranil uplne :)
Jsou tam prakticky 4 typy - zadny (explicitni) namespace, "mods", "ns1", "ns2".
ns2 myslim nekdy odkazuje jinam. Mozna to korektni je, ale proc je to takto komplikovane.
Je to vzdy MODS!, takze dava smysl pouzit jen implicitni namespace xmlns="http://www.loc.gov/mods/v3"
A v dokumentu pak namespacy neuvadet.
Naopak by davalo smysl pouzit jiny namespace pro ta vase rozsireni MODSu, coz ale (tusim) nedelate, protoze pro to snad ani neni vytvorene xml schema. Myslim, ze ani vytvorit neslo.

Kazdopadne by bylo dobre zbavit se zavislosti klientu na MODSu a rozsirit JSON v API /api/v5.0/item/UUID o udaje, ktere se ted musi prebirat z MODSu.
