### ISSUE TITLE
Sigla v shelfLocator v MODS

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#54]
Některé dokumenty mají v MODS v shelfLocator siglu před signaturou. Třeba u této mapy http://kramerius.mzk.cz/search/handle/uuid:64ac0900-a601-4899-860a-9f043f980042 je v MODS v shelfLocator toto: BOA001STMpa-1257.612

Mělo by tam být jen  "STMpa-1257.612". Ideální by bylo zjistit, kde to všude je a pak siglu z toho pole smazat.

**Comment by LenkaDamborska** [comment]
Tady je další příklad, tentokrát z novějších věcí - uuid:0a3ee50a-1991-4786-a7f1-6200db8a43da 
Přemýšlím, jak k tomu při té transformaci dojde. Záznam v Marcu vypadá standardně.

**Comment by pavluska** [comment]
Ahoj,

dojde k tomu jednoduse. Je chyba v prevodni sablone a spoji to cele pole
910 do jednoho pole v MODS.

P.

pá 29. 1. 2016 v 14:14 odesílatel LenkaDamborska <notifications@github.com>
napsal:

**Comment by LenkaDamborska** [comment]
To jo, ale právě to není u všeho, jen u některých záznamů - a ty vypadají stejně jako ty ostatní. Kdyby byla chyba v šabloně, tak to dělá u všeho, ne?

**Comment by pavluska** [comment]
To se zeptej kluku, at mrknou, jak to v tom editoru ted je. Jednu dobu to
takhle delalo, pak se to opravilo, ale pak se tam ta chyba pri nejakem
dalsim updatu zanesla znova myslim... A taky nemusi byt u vsech zaznamu 910
a.

so 30. 1. 2016 v 22:53 odesílatel LenkaDamborska <notifications@github.com>
napsal:

**Comment by MartinRumanek** [comment]
Bude to nejpíš novou konverzní šablonou z MARC21 do MODS, která jede podle RDA.

**Comment by LenkaDamborska** [comment]
Jo, to probadame (az po padajicim Krameriu). Divala jsem se na dva zaznamy delane ve stejne davce. Chyba byla jen v jednom, pricemz oba obsahovaly stejna pole vcetne 910a. Zkusim se jeste podivat, podle jakych pravidel se to delalo.

**Comment by jirikrepl** [comment]
[mapa afriky](http://kramerius.mzk.cz/search/i.jsp?pid=uuid:64ac0900-a601-4899-860a-9f043f980042#map-page_uuid:3eecf716-3cb5-4464-aa7b-a72e0fd1bcfe) a [Amos Komensky](http://kramerius.mzk.cz/search/i.jsp?pid=uuid:0a3ee50a-1991-4786-a7f1-6200db8a43da) mají špatný shelfLocator.

Zkusil jsem xslt transformaci programem [xsltproc](http://xmlsoft.org/XSLT/xsltproc.html) takto:

Ze zdrojového [AfrikaMarc](http://aleph.mzk.cz/OAI?verb=GetRecord&identifier=oai:aleph.mzk.cz:MZK03-001085278&metadataPrefix=marc21) jsem pomocí šablony [marc2mods](https://github.com/moravianlibrary/MEditor/blob/d001cd5e72ee917680b46aca6aca84014592b607/editor-common/editor-common-server/src/main/resources/MARC21slim2MODS3.xsl#L4-L4) vytvořil [AfrikaMods](https://gist.github.com/jirikrepl/c745c719abb473705020)

shelfLocator se vytvořil správně, správně se vytvoří i z monografie Amose

**Comment by jirikrepl** [comment]
Pro sysno 2610452400 se nastaví v GUI editoru v záložce MODS shelfLocator takto:

editor.staff.mzk.cz: BOA001Skř.1R-1248.852,16
medit.mzk.cz: BOA001Skř.1R-1248.852,16
localhost-superDevMode: Skř.1R-1248.852,16
localhost-tomcat: Skř.1R-1248.852,16

Můžeme mít nějak jinak nastavený editor? (configuration.properties)

**Comment by MartinRumanek** [comment]
V konfiguraci byly připojené staré šablony, opraveno.

**Comment by jirikrepl** [comment]
V ideálním případě se při buildu [docker image](https://github.com/moravianlibrary/MEditor/blob/master/dockerfile/meditor/Dockerfile#L34) použije šablona na řádku 34. 

My jsme ale překryli celý adresář resources (volumes v docker-compose.yml). Mezitím se v repozitáři opravila šablona. Takže editor.staff.mzk.cz používal starou šablonu.

**Comment by LenkaDamborska** [comment]
No a teď ještě opravit ty chybné hodnoty v shelflocator, které se do Krameria v mezičase dostaly. Je potřeba najít, kde se to objevuje a pak to smáznout. Takže já to znovu otvírám.

**Comment by LenkaDamborska** [comment]
No a teď ještě opravit ty chybné hodnoty v shelflocator, které se do Krameria v mezičase dostaly. Je potřeba najít, kde se to objevuje a pak to smáznout. Takže já to znovu otvírám.
