### ISSUE TITLE
Typ strany vyobrazení

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/MEditor#57]
Z porady 16.2. (Petr žabička, Martin Rumánek, Lenka Damborská, Jiří Dufka, Michal Indrák) vyplynulo, že:

- převezmeme z KNAV označení pro typ strany illustration, jako český ekvivalent navrhneme vyobrazení

- navrhneme zahrnutí KNAVkových typů stran do standardů přes formátový výbor pro NDK

- nový typ strany bude implementovaný do editoru s obecnou platností (pro všechny uživatele)

- typ strany se bude zobrazovat i uživatelům v klientovi

zapsal: Jirka

**Comment by LenkaDamborska** [comment]
Jen připomínka, že spíš se zeptám já KNAVky, jestli ty strany nějak řeší s NK a nastíníme to na nějakém setkání formátového výboru pro NDK. Prosazovat do standardu všechny ty typy stran od KNAV v plánu není.
