### ISSUE TITLE
Zálohovat db uložených struktur

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#6]
Bylo by velmi užitečné zálohovat relevantní položky v db, kde jsou uživateli uložené struktury. Teď se mažou s novou verzi Docker image.

**Comment by MartinRumanek** [comment]
Špatně se persistovala databáze - vyřešené. 

Nyní taky dochází k automatickému zálohování databáze - u tebe do adresáře /meditor-data/backup. Záloha se dělá jednou za den (v noci), jednou za týden (v neděli) a jednou za měsíc (1.)
