### ISSUE TITLE
V nove verzi nefunguje stahovani z X-services

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#60]
Po zadani SYSNO 000088411 a pokus stáhnout metadata (konkretne SKC) je výsledkem:
RPC failed:500 Internal Server Error The call failed on the server; see server log for details

![img](http://i.imgur.com/hYBX3WQ.png)

tag :devel

**Comment by jirikrepl** [comment]
Po zpomalení našeho internetu, vyhledání přes x-services zkončí chybovou hlaskou v gui
http://imgur.com/OpjtpDf

log: https://gist.github.com/jirikrepl/4e43a224bfb8c8ee536f

protokol oai taky nestahne metadata, v gui nevyhodi chybovou hlasku. (tabulka pro metadata zustane prazdna)

log: https://gist.github.com/jirikrepl/76d042f8c6724e2469cb

**Comment by jirikrepl** [comment]
update resteasy-client na verzi problem nevyresil 3.0.16

pro vyhledani `javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request` nenasel zadne reseni

mozna ze neni problem v knihovne resteasy, mozna editor nepocita s delsi prodlevou na pozadavek o stazeni metadat. 

mozna by se to dalo vyresit nejak takto
http://stackoverflow.com/questions/35700875/alternatives-to-sleep-when-checking-if-netty-server-is-up
https://en.wikipedia.org/wiki/Back-off_pattern
