### ISSUE TITLE
Nedostanu se do meditu po ukončení programu nestandardním způsobem

### ISSUE THREAD

**Issue by Lenyska** [moravianlibrary/MEditor#62]
Prosím o pomoc: 
Přiřazovala jsem v meditu 4 měsíce k již existujícímu ročníku 2006. Po vytvoření v Krameriu jsem pak v meditu přesunula měsíce, jak k sobě patří. Dala jsem publikovat a vše probíhalo celkem dobře. Poté jsem chtěla prázdný objekt smazat. Asi mě mělo zarazit, že má "vlákno", protože se ukázala tabulka s textem "has volume", ale i přesto jsem ho chtěla odstranit, protože bylo prázdné a nikde jsem nenašla, s čím souvisí. Odstraňování trvalo dost dlouho, tak jsem nakonec program sama zavřela, zkusila CTRL+F5 a od té doby se nemohu dostat do meditu. Ročník 2006 prázdný se mi stejně nesmazal.

**Comment by LenkaDamborska** [comment]
Dobrý den, přetrvává stále tento problém?
