### ISSUE TITLE
Nefunkční ingesty při výskytu dlouhých polí 245

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/MEditor#64]
Pokud se do metadat nahrává dlouhé pole s názvem (245), nezobrazuje se ingest. Protože zároveň není od poslední aktualizace funkční závěrečná stránka editace, je nutné čekat na nahrání dokumentu do Krameria, kde je dostupný stálý odkaz na dokument. Probíhá-li víc operací zároveň a tvoří se fronta, zdržuje se zpracování jednoho dokumentu až o několik minut. Problém bude zřejmě v převodu pole 245 s příliš velkým množstvím znaků z MARC21 do MODSu.

**Comment by jirikrepl** [comment]
OK potřebovali by jsme vědět jaké konkrétní data tohle dělají.

**Comment by jirduf** [comment]
V gitteru jsem poslal spoustu odkazů, psali jste že už jich máte dost:-(
V editoru jsem pro ten účel nechal v záložce graphics ČK 2610457238.

**Comment by jirikrepl** [comment]
"Protože zároveň není od poslední aktualizace funkční závěrečná stránka editace" -- tohle není dobré a měli by jsme to opravit

**Comment by jirduf** [comment]
však vám to říkám už dva měsíce :-) Pobav se s Lenkou, jak velká je to priorita.

**Comment by jirikrepl** [comment]
opraveno https://github.com/moravianlibrary/MEditor/pull/66

**Comment by jirduf** [comment]
pořád to dělají další dokumenty - např. 2610457911 (nechávám v editoru)

**Comment by LenkaDamborska** [comment]
Otestovat a nasadit.

**Comment by jirduf** [comment]
Maximální počet znaků v poli 245 je 1952 bez diakritiky.

**Comment by jirikrepl** [comment]
opraveno https://github.com/moravianlibrary/MEditor/commit/afec9f0c2fc992afaf48b59400bafe273073e0f0
