### ISSUE TITLE
Editor bez hlášení chyby nenahraje metadata

### ISSUE THREAD

**Issue by jirikrepl** [moravianlibrary/MEditor#65]
Tato sbírka se nahrála bez metadat: http://kramerius.mzk.cz/search/i.jsp?pid=uuid:fadf0027-7582-41ac-96d4-df547489deb1

Typ dokumentu: Graphic
Sysno:  001083976
báze MZK03
ČK 2610457266

**Comment by jirduf** [comment]
graphics

**Comment by jirikrepl** [comment]
@jirduf není to stejný problém s dlouhým polem title? Jáké sysno má tahle sbírka? Stejně jako tohle issue https://github.com/moravianlibrary/MEditor/issues/64

**Comment by jirduf** [comment]
Nevím, obvykle se při dlouhých názvech metadata nahrají, ale nezobrazí se ingest. Tady se metadata nenahrála. Sysno dokumentu je 001083976 v bázi MZK03, ČK 2610457266. PS: Co myslíš přesně sbírkou? Sbírka = dokument (tj. kniha, mapa, časopis ...)?

**Comment by jirikrepl** [comment]
Zkusil jsem vytvořit [dokument](http://krameriustest.mzk.cz/search/i.jsp?pid=uuid:b5d30225-0623-456a-b615-60709f7610e1) typu graphic se sysnem 001083976. Metadata jsou v pořádku.
