### ISSUE TITLE
Editor nezobrazí dokument po dokončeném ingestu

### ISSUE THREAD

**Issue by jirikrepl** [moravianlibrary/MEditor#70]

**Comment by jirikrepl** [comment]
opraveno https://github.com/moravianlibrary/MEditor/pull/71

**Comment by jirduf** [comment]
Bohužel to nefunguje vždy. Po uzavření issue se objevily další obdobné případy - např. dokument s ČK 2610457877.

**Comment by LenkaDamborska** [comment]
Nasadit.
