### ISSUE TITLE
Neexistující informace o ingestu, dokument nahraný v Krameriovi

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/MEditor#72]
Jde o dokument 001084003 v editoru ve složce graphic. Při pokusu o zobrazení informace o ingestu hlásí: "Během zpracování požadavku došlo k chybě. Soubor s informacemi o ingestu pro tento adresář neexistuje, nebo není validní." V Krameriovi je to nahrané v pořádku.

**Comment by jirduf** [comment]
totéž u 2610398076

**Comment by jirikrepl** [comment]
Není to stejný problém jako https://github.com/moravianlibrary/MEditor/issues/70?

**Comment by MartinRumanek** [comment]
Není, informace o Ingestu se dají zobrazit v menu ve frontě (pravý klik na dokumentem)

**Comment by jirikrepl** [comment]
Zavírám, tuto chybu jsme nedokázali replikovat
