### ISSUE TITLE
nezobrazuje se celá signatura

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/MEditor#74]
V Krameriovi se zobrazuje jen část signatury, obvykle jen ve tvaru lokace-1234.567 Vše co následuje, chybí. Příklad zde: http://kramerius.mzk.cz/search/handle/uuid:83ecea28-c820-420f-add3-6c6222cacca4 Záznam zde: https://vufind.mzk.cz/Record/MZK03-001091278. Tento stav dost ztěžuje identifikaci i vyhledávání.

**Comment by LenkaDamborska** [comment]
@jirikrepl Jirko, vem si to na starosti a zařaď do fronty.

**Comment by jirikrepl** [comment]
OK zavírám to tady, budu pokračovat zde https://github.com/moravianlibrary/kramerius/issues/95

**Comment by LenkaDamborska** [comment]
Šablona upravena. Nové chyby už by vznikat neměly.

**Comment by MartinRumanek** [comment]
Náhodou jsem přišel na to, že tato šablona se na našem editor.staff vůbec nepoužívá.

**Comment by MartinRumanek** [comment]
Šablona byla nasazena při opravě issue #106
