### ISSUE TITLE
Po poslednim update se v generovanych JPEG2000 vyrazne pritvrdil kontrast

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#75]
Doslo k nejake zmene v nastaveni konverze?
viz
http://www.digitalniknihovna.cz/mkct/view/uuid:bc5dd00c-6261-4677-b231-59df1a95f138?page=uuid:35cf514a-d8f9-4cfa-807a-7eeceda6a9ea

http://www.digitalniknihovna.cz/mkct/view/uuid:bc5dd00c-6261-4677-b231-59df1a95f138?page=uuid:bc8a98fa-70c1-40e8-80e5-8574b53b018f

http://www.digitalniknihovna.cz/mkct/view/uuid:bc5dd00c-6261-4677-b231-59df1a95f138?page=uuid:d47e4e62-374e-49a9-999f-5791741dba07

**Comment by MartinRumanek** [comment]
Nedošlo, ale pošli mi prosím sem (nebo na mail) zdrojový obrázek (stačí jeden, ideálně ten, na kterém to jde nejvíce vidět).

**Comment by black23** [comment]
[Archiv.zip](https://github.com/moravianlibrary/MEditor/files/244685/Archiv.zip)
