### ISSUE TITLE
Náhledy stránek při tvorbě struktury dokumentu se nezobrazují

### ISSUE THREAD

**Issue by jrihak** [moravianlibrary/MEditor#80]
Popis problému:

Po vyhledání záznamu dokumentu přes OAI-PMH se spustí konverze vstupních obrazových souborů do JPEG2000 a poté se zobrazí obrazovka pro tvorbu struktury dokumentu, kde se zároveň přiřazují jednotlivým stránkám jejich typy. Místo náhledů jednotlivých stránek se ale zobrazí pouze rámeček náhledu s ikonou obrázku (mime type ikona). 

V logu meditoru (docker-compose logs) není žádná chyba s tímto spojená, v debugovací konzoli Google Chrom v záložce Console se ale výpíše následující chyba pro každý požadavek na náhled stránky:

`/djatoka/resolver?url_ver=Z39.88-2004&svc_id=info:lanl-repo/svc/getRegion&s…00&svc.level=2&svc.scale=110&rft_id=2ba70698-4657-34bf-ba10-1c0b41ad1b2f:1 GET http://digi-workflow.ntkcz.cz/djatoka/resolver?url_ver=Z39.88-2004&svc_id=i…2000&svc.level=2&svc.scale=110&rft_id=2ba70698-4657-34bf-ba10-1c0b41ad1b2f net::ERR_CONNECTION_REFUSED`

Po zkopírování URL adresy GET požadavku ([http://digi-workflow.ntkcz.cz/djatoka/resolver?url_ver=Z39.88-2004&svc_id=info:lanl-repo/svc/getRegion&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.level=2&svc.scale=110&rft_id=2ba70698-4657-34bf-ba10-1c0b41ad1b2f](url)) se zobrazí chybová hláška "Tento web není dostupný".

Pokud ale přepíšu začátek url na 'https://', tak se náhled obrázku korektně zobrazí.

Zkoušel jsem upravit adresu serveru kde běží docker (v docker-compose.yml) na 'https://digi-workflow.ntkcz.cz/meditor' (místo původně uvedeného 'http://digi-workflow.ntkcz.cz/meditor) a pomocí `docker-compose stop && docker-compose rm && docker-compose up -d` jsem kontejnery vypnul, odstranil a znovu nahrál a spustil, ale ne tuto chybu to nemělo žádný vliv.

Předpokládané chování:

Meditor bude zasílat požadavek na platnou URL adresu s protokolem 'https://'.

Jakub Řihák
NKT

**Comment by jdobiasovsky** [comment]
Ahoj, nějaký postup v řešení? Zatím se na naší straně nic nezměnilo a trochu nás to tu brzdí... :-/

**Comment by jirikrepl** [comment]
Dobrý den,
@jdobiasovsky včera jsem si všiml tohoto issue, začínám na tom pracovat. 

@jrihak jaké jméno proměnné v docker-compose.yml jste přepsal z *http* na *https*? `imageServer.url`? díky

**Comment by jirikrepl** [comment]
Je možné, že toto není chyba editoru. Bohužel se nám nepodařilo tento problém zreplikovat. Zavírám toto issue. Jinak jediné, co nás napadá je, že by jste mohli seznámit s kódem editoru a zkusit si problém sami odladit (remote debug)
