### ISSUE TITLE
Tečka/pomlčka v konfiguraci

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#85]
Poslední verze neměla dořešené tečky/pomlčky v konfiguraci a nefungoval import do Krameria. Proběhla oprava ve verzi v openshiftu, tam už je to ok. Dořešit ještě opravu na dockeru + napsat sem aktuální stav.

**Comment by LenkaDamborska** [comment]
@jirikrepl na Gitteru: 
udělali jsme hotfix issue konfigurace s tečkami. Tento hotfix je zahrnutý docker imagi s tagem dot-fix zde: https://hub.docker.com/r/moravianlibrary/meditor/tags/ (přepište si tag ve vašem docker-compose.yml a dejte docker pull)
Pro odvážné, zde jsou vidět změny kódu (poslední 2 commity): https://github.com/moravianlibrary/MEditor/commits/docker.dot.issue
Ve vašem docker-compose.yml je potom nutné nahradit proměnné s tečkami proměnnými s podtržítky např. imageserver.url => imageserver_url

**Comment by jirikrepl** [comment]
Udělali jsme hotfix issue "konfigurace s tečkami". Tento hotfix je zahrnutý v docker image s [tagem dot-fix](https://hub.docker.com/r/moravianlibrary/meditor/tags/) (přepište si tag ve vašem *docker-compose.yml* a dejte `$ docker-compose pull`)

Ve vašem *docker-compose.yml* je potom nutné nahradit proměnné s tečkami proměnnými s podtržítky např. `imageserver.url` => `imageserver_url`

**Comment by MartinRumanek** [comment]
Není mergnuto do master větve.

Nicméně v aktuálním docker-compose je možné bez problému používat tečku, v Openshiftu jsou pomlčky nutné, viz https://github.com/moravianlibrary/s2i-kramerius/issues/1
