### ISSUE TITLE
Problém s editorem NTK

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#86]
Meditor nezobrazuje položky ve vstupní frontě, ukazuje se jenom monograph, ale periodicals i s obsahem chybí. Složka monograph je sice vidět, ale pokud se do ní nahrají soubory, tak nejsou vidět (ani po refreshi).

@jirikrepl, co s tím můžeme na straně MZK ještě udělat?

**Comment by jirikrepl** [comment]
@jdobiasovsky vytvořili jsme toto issue podle vašeho popisu z gitteru. 

Zatím se nám nepodařilo u nás vaše issue zreplikovat.

Používáte tento image `image: moravianlibrary/meditor:latest`? Napadá nás, že možná se vám nenastaví proměnná `documentTypes`, která má pak takovou [výchozí hodnotu](https://github.com/moravianlibrary/MEditor/wiki/Configuration-Properties-File).

Zkuste prosím "backslashovat" hodnotu proměnné takto: 
`documentTypes=monograph\, periodical\, map\, soundrecording`

**Comment by jdobiasovsky** [comment]
Ano, image mám nastavený na ` image: moravianlibrary/meditor:latest`. Backslashování hodnot také nepomohlo.

V odkazu na výchozí hodnoty documentTypes jsem si všimnul že jsou nastavené na `periodical, monograph`. Ne naopak. Vyzkoušel jsem tedy také tuto možnost a teď Meditor složku vidí (zobrazují se jako monograph a periodical\). Nicméně její obsah ne, ani po refreshi.

**Comment by jirikrepl** [comment]
Není možné, že máte špatně nastavené práva? Tohle nevypadá na chybu editoru. U nás se ji nepodařilo replikovat. Co se stane když "vlezete" do kontejneru editoru a zkusíte načíst nějaký soubor z importních složek?

    $ docker exec -it <nazev_editor_kontejneru> bash
    $ head <importni_slozka>/obrazek.tiff

**Comment by jdobiasovsky** [comment]
`
[workflow@digi-workflow editor]$ docker exec -it editor_meditor_1 bash
<al/000629702_1920_1921_02_05/000629702_1920_1921_02_05_0001.tif               
head: cannot open 'smb://moon.ntkcz.cz/scan/DIGITALIZACE/EDITOR/periodical/000629702_1920_1921_02_05/000629702_1920_1921_02_05_0001.tif' for reading: No such file or directory
`

Daný postup zobrazuje "No such file or directory". Nicméně složky monograph i periodical mají stejná přístupová práva a jsou i v pořádku namountovány, takže se do nich dá přes příkazový řádek dostat.

`
[workflow@digi-workflow EDITOR]$ ls -l
celkem 0
drwxrwxr-x+ 2 workflow workflow 0 28. čec 10.57 monograph
drwxrwxr-x+ 3 workflow workflow 0 28. čec 11.06 periodical
drwxrwxr-x+ 2 workflow workflow 0 28. čec 11.04 periodical\
`
Třetí složka `periodical\` se objevila při nastavení documentTypes = periodical, monograph. Předtím byly hodnoty opačně

**Comment by jdobiasovsky** [comment]
Restartoval jsem meditor příkazy `docker-compose stop && docker-compose rm -f && docker-compose up -d`. V docker-compose.yml jsou hodnoty `documentTypes = periodical, monograph`

Meditor nyní vidí pouze periodicals včetně podsložek, ale po spuštění editace vyskočí hláška: 
"No images found in /data/meditor/input/periodical/000629702_1920_1921_02_05/ Chcete provést akci znova?"

Akce Znovu načíst vstupní frontu v logu hlásí chybu:
`ERROR (FedoraAccessImpl.java:866) - model:periodical in not in the repository, please insert this model first!Failed to access the WSDL at: file:/home/kreplj/code/moravianlibrary-meditor/editor-common/editor-common-server/src/wsdl/FedoraAPI-M.wsdl.`

Celá hláška tady:
[queue_refresh.txt](https://github.com/moravianlibrary/MEditor/files/390328/queue_refresh.txt)

**Comment by jirikrepl** [comment]
Dobře co se stane, když backslashujete i u proměnné imageExtension? `docker-compose.yml` by potom mohl vypadat třeba takto:

    environment: 
      ...
      - documentTypes=monograph\, periodical\, map\, soundrecording
      - imageExtension=jpg\, JPG\, png\, tiff\, tif\, jpeg\, jp2\, pdf\, wav\, mp3\, ogg
      ...

**Comment by jirikrepl** [comment]
Dobře, projevila se nám stejná chyba, budu na tom pracovat od úterý a pak dám vědět.

**Comment by jirikrepl** [comment]
Dobrý den,
udělal jsem opravu, mělo by to fungovat. Stačí když si stáhnete docker image s tagem [dot-fix](https://hub.docker.com/r/moravianlibrary/meditor/tags/) a potom znovu vytvoříte docker kontejner

**Comment by jdobiasovsky** [comment]
Dobrý den,
udělal jsem co jste říkal a zdá se že všechno zase normálně funguje. 

Děkujeme

**Comment by LenkaDamborska** [comment]
Dobře, zavíráme.
