### ISSUE TITLE
Přetahování obrázků v sheetmusic

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#87]
U dokumentů v modelu sheetmusic nelze přetahovat obrázky na objekt ve struktuře. 
Objeví se hláška: Tento digitální objekt můžete přetáhnout jen na objekt, který může obsahovat objekt typu: page..

**Comment by jirikrepl** [comment]
Na [tomto řádku][1] se kód dotazoval na možné potomky. Pro model sheetmusic nebyli potomci definovaní. Proto docházelo k chybě.

[1]: https://github.com/moravianlibrary/MEditor/blob/4093e091089bb3408c3486ed71a771827325fb9d/editor-creation/src/main/java/cz/mzk/editor/client/view/CreateObjectMenuView.java#L322-L322

**Comment by LenkaDamborska** [comment]
Jak to vypadá??

**Comment by LenkaDamborska** [comment]
Opraveno.
