### ISSUE TITLE
MZK03 dokumenty - ukládání na imageserver

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#88]
Vše z MZK03 báze má teď sysno ve tvaru mzk03xxxxxxxxx a ukládá se to na imageserveru do složky "meditor". Bude potřeba vymyslet, aby se to ukládalo do složky "mzk03" v klasické sysnové struktuře. A taky bude potřeba přesunout stávající mzk03 dokumenty ze složky meditor do mzk03.

**Comment by jirikrepl** [comment]
Už to asi nestihnu, ale je potřeba upravit kód na [tomto místě](https://github.com/moravianlibrary/MEditor/blob/4093e091089bb3408c3486ed71a771827325fb9d/editor-common/editor-common-server/src/main/java/cz/mzk/editor/server/newObject/CreateObject.java#L379-L379). Zde se editor rozhoduje jestli jde o sysno.

Pro sysno `mzk03xxxxxxxxx` je volání funkce `isSysno()` `false`

**Comment by jirikrepl** [comment]
Opraveno v 29e660b3547a0c8bc80931671c88a36c3e1f56ca

**Comment by MartinRumanek** [comment]
Není to implementované úplně dobře, špatně se to nasekává do struktury na imageserveru.
