### ISSUE TITLE
Editor nenačte dříve uloženou stromovou strukturu stránek.

### ISSUE THREAD

**Issue by jirikrepl** [moravianlibrary/MEditor#90]
Editor nenačte dříve uloženou stromovou strukturu stránek.

Na stránce s otevřenou monografií a nahranými metadaty. Po kliknutí na ikonu diskety -> načíst... -> vybrání řádku z tabulky-> tlačítko načíst

```
$ docker-compose logs

DEBUG (StoreTreeStructureHandler.java:94) - Processing action: StoreTreeStructureResult role:StoreTreeStructureAction[GET,3621,false,cz.mzk.editor.shared.rpc.TreeStructureBundle@1baa99f4]
ERROR (TreeStructureDAOImpl.java:307) - DB has not been updated! SELECT * FROM tree_structure_node WHERE tree_structure_id = (3621) ORDER BY id
```

Obrázek s oknem načítání. Po stisknutí tlačítka načíst "se nic nestane".
![selection_045](https://cloud.githubusercontent.com/assets/2588479/18626374/fa93409e-7e54-11e6-92e5-37a5f4c9df4e.png)

**Comment by jirikrepl** [comment]
Následující postup nenačte stránky:

1. uložení práce tak, že do levého stromu *nebyly* přetaženy všechny strany
2. načtení uložené práce neproběhne v pořádku, zobrazí se chyba

kód selhával na [tomto řádku](https://github.com/moravianlibrary/MEditor/blob/e036fbedea33a88c3528bf52c808a09826b463df/editor-creation/src/main/java/cz/mzk/editor/client/presenter/CreateStructurePresenter.java#L1561-L1561) v případě, kdy pole `TreeNode[] tree` "nebylo celé obazené"

`TreeNode[] tree` se vytváří [zde](https://github.com/moravianlibrary/MEditor/blob/e036fbedea33a88c3528bf52c808a09826b463df/editor-creation/src/main/java/cz/mzk/editor/client/view/window/LoadTreeStructureWindow.java#L415-L415).

Takto kód skončí chybou:

    TreeNode[] tree = new TreeNode[2];
    tree[0] = node;
    // tree[1] není obsazený

Možná je to i bug ve SmartGwt, to jsem nezkoušel. V editoru jsem upravil jsem kód tak https://github.com/moravianlibrary/MEditor/commit/f09c4fd49ee0a85528c51b097dc3c1fba9bd5f78, aby pole "mělo přesnou velikost".

**Comment by MartinRumanek** [comment]
Není mergnuto v master větvi.
