### ISSUE TITLE
Firefox: při otevření dokumentu po publikaci - chybová hláška "Connection cannot be established. Please check whether Fedora is running."

### ISSUE THREAD

**Issue by jirikrepl** [moravianlibrary/MEditor#93]
Chybová hláška se zobrazí pouze ve Firefoxu, ve Chromu ne.

Chybová hláška "Connection cannot be established. Please check whether Fedora is running." se zobrazí po publikaci dokumentu a po jeho následném zobrazení. 

Pouze ve Firefoxu má proměnná `uuid` na [tomto řádku](https://github.com/moravianlibrary/MEditor/blob/e036fbedea33a88c3528bf52c808a09826b463df/editor-common/editor-common-server/src/main/java/cz/mzk/editor/server/handler/GetDigitalObjectDetailHandler.java#L161-L161) hodnotu např. `uuid%253A34803d50-5042-11e3-8cdc-005056827e51` a ne správně s dvojtečkou `uuid:34803d50-5042-11e3-8cdc-005056827e51`. Vypadá to, jako vy proměnná nabyla hodnoty z URL kde dvojtečka je kódovaná jako %253A. 

Potom kód selže na zmiňovaném řádku a zobrazí chybovou hlášku.

**Comment by LenkaDamborska** [comment]
Taky mi nejde přetahování obrázků pod objekt ve Firefoxu. Takže zatím používat Chrome.

**Comment by MartinRumanek** [comment]
Vyřešeno aktualizací GWT.
