### ISSUE TITLE
Náhledy pro PDF, které jsou ve CMYK

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/MEditor#95]
Při importu PDF do Krameria, MEditor vytváří náhled, většinou to funguje správně, ale je problém s PDF, která jsou v barevné paletě CMYK (nachystané pro tisk).

např. pro teď importované  PDF 2610662645 se udělá náhled v negativu

![img](http://i.imgur.com/2MmLOa7.png)

Můžeme se vydat třemi cestami:
- PDF se budou před nahráním do Editoru konvertovat do RGB (stejně jako obrázky na vstupu musí být vždy RGB)
- editor se naučít detekovat CMYK pdf a naloží s něma jinak
- vůbec se nebudou vytvářet náhledy, ale hodí se tam nějaký defaultní obrázek - tak to myslím dělá proarc, ale moc se mi to nelíbí :)

**Comment by MartinRumanek** [comment]
Další problém, který při generování náhledu utilitou ImageMagick z PDF nastává:

![nahled](http://i.imgur.com/GdLjIyg.png)

(prázdná strana vlevo pře d náhledem).

**Comment by LenkaDamborska** [comment]
Hm :/

**Comment by MartinRumanek** [comment]
Místo ImageMagicku se použije knihovna PdfBox, která konverze různých PDF zvládá lépe.
