### ISSUE TITLE
Nelze načíst uloženou strukturu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#98]
Při pokusu vyučít již vytvořenou a uloženou strukture to není možné, tlačítko Načíst není aktivní.
![cabcjcch](https://cloud.githubusercontent.com/assets/5516936/21719914/7dc97174-d420-11e6-8704-9dbeaf146b5b.png)

**Comment by MartinRumanek** [comment]
Není možné načítat strukturu už v okně načítaní metadat. Struktura jako taková neobsahuje metadata.

Po načtení metadat se mi nedaří tuto chybu replikovat.
